---
# Common config
- include_vars: secrets.yml

- name: Install Fail2Ban
  apt:
    name: fail2ban
    state: present
- name: Copy fail2ban config
  template:
    src: jail.local
    dest: /etc/fail2ban/jail.local
    mode: 0644
- name: Restart fail2ban
  service:
    name: fail2ban
    state: restarted

# Secrets / parameterized config
- name: Write envar {{ item.key }}
  lineinfile:
    path: /etc/environment
    regexp: "^{{ item.key }}"
    line: '{{ item.key }}="{{ item.value }}"'
  loop:
    - key: DJANGO_SECRET_KEY
      value: "{{ DJANGO_SECRET_KEY }}"
    - key: PGUSER
      value: "{{ PGUSER }}"
    - key: PGPASSWORD
      value: "{{ PGPASSWORD }}"
    - key: SENDGRID_API_KEY
      value: "{{ SENDGRID_API_KEY }}"
    - key: AWS_ACCESS_KEY_ID
      value: "{{ AWS_ACCESS_KEY_ID }}"
    - key: AWS_SECRET_ACCESS_KEY
      value: "{{ AWS_SECRET_ACCESS_KEY }}"
    - key: RAVEN_DSN
      value: "{{ RAVEN_DSN }}"
    - key: PAPERTRAIL_HOSTNAME
      value: "{{ PAPERTRAIL_HOSTNAME }}"
    - key: PAPERTRAIL_PORT
      value: "{{ PAPERTRAIL_PORT }}"
    - key: PAPERTRAIL_URL
      value: "{{ PAPERTRAIL_URL }}"
